#!/bin/bash
# I might add some comments later
set -euo pipefail

CONFIG="$HOME/.config/rsyncraft/config.conf"

if [ ! -f "$CONFIG" ]; then
    echo "Error: Config file not found: $CONFIG" >&2
    echo "Run ./rsyncraftinstall.sh first." >&2
    exit 2
fi

source "$CONFIG"

if [ $# -eq 0 ]; then
    echo "Error: No SSH server provided." >&2
    echo "Usage: $0 [-p] -s root@server" >&2
    exit 2
fi

SERVER=""
PACLIST=0

while getopts "s:ph" opt; do
    case "$opt" in
        s)
            SERVER="$OPTARG"
            ;;
        p)
            PACLIST=1
            ;;
        h)
            echo "Usage: rsyncraft -s root@server [-p] [-h]"
            echo
            echo "-s SERVER    SSH server to back up to"
            echo "-p           Generate installed package lists"
            echo "-h           Show this help message"
            exit 0
            ;;
        \?)
            echo "Error: Invalid option: -$OPTARG" >&2
	    echo "Usage: rsyncraft -s root@server [-p] [-h]"
            echo
            echo "-s SERVER    SSH server to back up to"
            echo "-p           Generate installed package lists"
            echo "-h           Show this help message"
            exit 2
            ;;
        :)
            echo "Error: Option -$OPTARG requires an argument." >&2
            exit 2
            ;;
    esac
done

if [[ ! "$SERVER" =~ ^root@[a-zA-Z0-9.-]+$ ]]; then
    echo "Error: Invalid format '$SERVER'." >&2
    echo "Please use the format: root@server" >&2
    exit 2
fi

if [[ "$PACLIST" -eq 1 ]]; then
echo "Making package lists..."
mkdir -p ~/rsyncraft
case "$(command -v pacman >/dev/null && echo pacman; command -v apt >/dev/null && echo apt; command -v dnf >/dev/null && echo dnf)" in
    pacman)
	echo "file generated by rsyncraft for pacman" > "$HOME/rsyncraft/packages.txt"
        pacman -Qeq >> "$HOME/rsyncraft/packages.txt"
        pacman -Qmq > "$HOME/rsyncraft/aurlist.txt";;
    apt)
        echo "file generated by rsyncraft for apt/dpkg" > "$HOME/rsyncraft/packages.txt"
        dpkg --get-selections >> "$HOME/rsyncraft/packages.txt";;
    dnf)
	echo "file generated by rsyncraft for dnf/rpm" > "$HOME/rsyncraft/packages.txt"
	dnf repoquery --installed --qf '%{name}' >> "$HOME/rsyncraft/packages.txt";;
esac
else
    echo "Skipping package lists"
fi
echo "Syncing to SSH server $SERVER..."

if rsync -aAHK --info=progress2 --delete "$BACKUP_SOURCE"/ "$SERVER":"$BACKUP_DEST"; then
    echo "Done!"
else
    rsync_status=$?
    if [ $rsync_status -eq 24 ]; then
        echo "Done (some temporary cache files vanished during the sync, which is normal)."
    else
        echo "Error: rsync failed with exit code $rsync_status" >&2
        exit $rsync_status
    fi
fi
